Include Git repositories and applications initialization
IBM/dbb-git-migration-modeler pull request #21
Opened 2024-11-05 10:51 UTC by M-DLB

This PR adds the support for the initialization of Git repositories and applications' packages, using a full build with preview and a packaging of the artifacts tat are already present in the provided datasets.
Rework of the documentation is started, to simplify it and ease the accessibility.

2024-11-08 15:51 UTC, dennis-behm requested changes
Hi @M-DLB I have reviewed the updates. Great enhancements. Can you please take a look to my comments, please?

2024-11-08 15:51 UTC, dennis-behm commented on src/groovy/assessUsage.groovy
>  							applicationDescriptorUtils.writeApplicationDescriptor(updatedTargetApplicationDescriptorFile, targetApplicationDescriptor)
This is more a general observation. The assessment phase does not explicitly tells about the actions that it takes.

We have
```
	==> 'sortcode' is owned by the 'CBSA' application
	==> Moving Include File 'sortcode' with usage 'private' to Application 'CBSA' described '/u/dbehm/git/dbb-git-migration-modeler-work/applications/CBSA/applicationDescriptor.yml'.
```

Would be good to have something like this
```
	==> 'sortcode' is owned by the 'CBSA' application
        ==> Moving Include File 'sortcode' to '/u/dbehm/git/dbb-git-migration-modeler-work/applications/CBSA/src/copy/sortcode.cpy'
	==> Adding Include File 'sortcode' with usage 'private to application descriptor for Application 'CBSA' '/u/dbehm/git/dbb-git-migration-modeler-work/applications/CBSA/applicationDescriptor.yml'.
	==> Removing Include File 'sortcode' from application descriptor for Application 'Unassigned' '/u/dbehm/git/dbb-git-migration-modeler-work/applications/Unassigned/applicationDescriptor.yml'.
	==> Adding Include File 'sortcode' to Migration Mapping file 'CBSA' '/u/dbehm/git/dbb-git-migration-modeler-work/configs/CBSA.mapping'.
	==> RemovingInclude File 'sortcode' to Migration Mapping file 'CBSA' '/u/dbehm/git/dbb-git-migration-modeler-work/configs/CBSA.mapping'.

```

2024-11-08 15:51 UTC, dennis-behm commented on src/groovy/extractApplications.groovy
> +		applicationDescriptorUtils.addBaseline(applicationDescriptor, "release/${mappedApplication.baseline}" as String, mappedApplication.baseline)
Only the main branch is initialised in the init step. I think we should not assume the release maintenance branch yet.

2024-11-12 13:51 UTC, M-DLB commented on src/groovy/extractApplications.groovy
> +		applicationDescriptorUtils.addBaseline(applicationDescriptor, "release/${mappedApplication.baseline}" as String, mappedApplication.baseline)
We could also initialize the release maintenance branch actually

2024-11-12 14:00 UTC, M-DLB commented on samples/applicationsMapping.yaml
> +    baseline: "rel-2.1.0"
I think it's OK to have different versions, to showcase how we can initialize applications and their Git repo with a specific version number. Agreed though that most of the applications should start as 1.0.0.

2024-11-12 14:00 UTC, M-DLB commented on samples/applicationsMapping.yaml
> +    baseline: "rel-1.4.0"
I think it's OK to have different versions, to showcase how we can initialize applications and their Git repo with a specific version number. Agreed though that most of the applications should start as 1.0.0.

2024-11-12 14:25 UTC, M-DLB commented on src/scripts/Migration-Modeler-Start.sh
> +	#### Summary
Yes I agree that this is the result of the Usage Assessment phase. However, this summary is meant to provide guidance after the execution of the Migration-Modeler-Start script, with the computed order in which to "load" Git repositories in the Git server, so this step only makes sense if the 5th step has been accomplished. I think we can leave it at the end of the process, as a "Next Step" guide.

2024-11-12 14:26 UTC, M-DLB commented on Setup.sh
> +PIPELINE_CI=AzureDevOps
Yes I can change that. Having the full name was convenient, but it can introduce errors when typing the chosen name.

2024-11-12 14:27 UTC, M-DLB commented on src/groovy/assessUsage.groovy
>  							applicationDescriptorUtils.writeApplicationDescriptor(updatedTargetApplicationDescriptorFile, targetApplicationDescriptor)
It feels like a lot written in the log. Would it be better to keep the message like this and thoroughly document this in the README instead?

2024-11-13 12:35 UTC, dennis-behm reviewed
@M-DLB one more comment please - can we replace with general credentials?

2024-11-13 12:35 UTC, dennis-behm commented on Setup.sh
>  ARTIFACT_REPOSITORY_USER=admin
```suggestion
ARTIFACT_REPOSITORY_USER=user
```

2024-11-13 12:35 UTC, dennis-behm commented on Setup.sh
> +ARTIFACT_REPOSITORY_PASSWORD=artifactoryadmin
```suggestion
ARTIFACT_REPOSITORY_PASSWORD=password
```

2024-11-13 17:05 UTC, dennis-behm approved these changes
Thank you @M-DLB

2024-11-13 17:09 UTC, merged