Provide jsonschema files for syntax validation and completion
IBM/dbb-git-migration-modeler pull request #23
Opened 2024-11-26 15:13 UTC by dennis-behm

This is delivering the jsonschemas for

* Application Descriptor 
* Application Mapping 
* Repository Path Mapping

This enables developers to have a better experience when customising the files

2024-12-02 14:18 UTC, M-DLB requested changes
Some comments - Thank you Dennis for starting this!

2024-12-02 14:18 UTC, M-DLB commented on schema/README.md
> +This folder contains the jsonschema files to be used by developers to enable their preferred YAML editor to perform syntax validation and completion.
```suggestion
This folder contains the jsonschema files to be used by the DBB Git Migration Modeler users when performing syntax validation and completion with their preferred YAML editor.
```

2024-12-02 14:18 UTC, M-DLB commented on schema/README.md
> +| [application-descriptor-schema.json](application-descriptor-schema.json) | Schema for Application Descriptor files |
```suggestion
| [application-descriptor-schema.json](application-descriptor-schema.json) | Schema for Application Descriptor file |
```

2024-12-02 14:18 UTC, M-DLB commented on schema/README.md
> +Please follow the instructions of your preferred YAML editor. The below bullets
```suggestion
Usage instructions differs depending on your preferred YAML editor.
```

2024-12-02 14:18 UTC, M-DLB commented on schema/README.md
> +## VS Code YAML extension
```suggestion
### VS Code YAML extension
```

2024-12-02 14:18 UTC, M-DLB commented on schema/README.md
> +To code YAML in VS Code, most users take advantage of the [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension by Red Hat.
```suggestion
To code YAML in VS Code, most users take advantage of the [RedHat YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension. 
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +            "description": "Unique name of the application w/o blanks or special characters. Used as by other applications to reference it.",
```suggestion
            "description": "Unique name of the application (without blanks or special characters). Used as by other applications to reference it.",
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +                                    "description": "Name of the file w/o file extension. Capitalization has to meet how the file is stored in the repository."
```suggestion
                                    "description": "Name of the file without file extension. Capitalization has to meet how the file is stored in the repository."
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +                                    "description": "The usage of the file impacts how build outputs for the file are packaged. Case-sensitive. \nInclude files with usage set to 'public' or 'shared' c
Not sure we should detail the purpose of the value here, since it's documented already.

```suggestion
                                    "description": "The usage of the file impacts how build outputs for the file are packaged. Case-sensitive. More information on this documentation section: https://github.com/IBM/dbb-git-migration-modeler/blob/main/AdvancedInformation.md#the-assessment-phase",
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +                                        "undefined"
Undefined is not valid, unused is.
```suggestion
                                        "unused"
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +            "description": "A list of baseline references used by the baseline option for impact builds. This is not yet used in automation tasks.",
```suggestion
            "description": "A list of baseline references used by the baseline option for impact builds. This may be used by future automation tasks.",
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +                        "description": "Branch reference of the application"
```suggestion
                        "description": "Branch name for which the baseline is set"
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +                        "description": "Baseline reference for build framework"
```suggestion
                        "description": "Baseline reference for the given branch"
```

2024-12-02 14:18 UTC, M-DLB commented on schema/application-descriptor-schema.json
> +                        "description": "The name of the consumer application."
```suggestion
                        "description": "The name of the consuming application."
```

2024-12-02 14:40 UTC, dennis-behm commented on schema/repository-paths-mapping-schema.json
> +              "description": "The type of artifacts under this group.",
I specifically called out the two options because it's an important keyword in the Application Descriptor and the further processing in Migration Modeler - 

https://github.com/IBM/dbb-git-migration-modeler/blob/main/src/groovy/assessUsage.groovy#L115

2024-12-02 14:42 UTC, dennis-behm commented on schema/application-descriptor-schema.json
> +                                    "description": "The usage of the file impacts how build outputs for the file are packaged. Case-sensitive. \nInclude files with usage set to 'public' or 'shared' c
I would like to combine the two. Having some details and a reference to the doc is both worth it.

2024-12-03 09:39 UTC, M-DLB commented on schema/repository-paths-mapping-schema.json
> +              "description": "The type of artifacts under this group.",
Right, agreed, but since there may be other values, would YAML file be considered as invalid if other values are used?

2024-12-03 10:01 UTC, dennis-behm commented on schema/repository-paths-mapping-schema.json
> +              "description": "The type of artifacts under this group.",
For the syntax validation of the YAML editors it will cause a warning. But the processing is not affected.

2024-12-10 16:26 UTC, M-DLB approved these changes
Thank you @dennis-behm for adding these definitions

2024-12-12 09:37 UTC, merged