Support for Db2 metadatastore
IBM/dbb-git-migration-modeler pull request #25
Opened 2024-12-05 16:20 UTC by M-DLB

This PR adds the support of the Db2 Metadatastore as a backend for storing the collections and scanning the logical files.
This PR also changes the way the parameters are passed between scripts, it is introducing the use of "-c" parm in every shell script.
It introduces the CheckDb2MetadataStore shell and groovy scripts, to check for the connection to the Db2 MetadataStore after setting it up.
The Setup script was enhanced to help the user specify the type of MetaDatastore, and asks related information if using file-based or Db2-based MetadataStore.
Finally, the 0-environment.sh script was enhanced with a new parm (-v) to check against a specific DBB Toolkit version installed.

2025-01-31 15:58 UTC, dennis-behm requested changes
Thanks for your hard work on this PR!

I think we can **simplify** how we pass in the various properties into the scripts and groovy code, which this PR clearly shows.

Why not just pass in the modeller config and read it as a properties file in the specific tasks? And have a section in each script to assert the required properties. Should be simpler, and makes it a bit lighter.

Additionally. I would like to add a "minimum" required DBB version . It will not work with DBB 2.0.x because of the build groups that you are introducing.

2025-01-31 15:58 UTC, dennis-behm commented on AdvancedInformation.md
> +| DBB_MODELER_DB2_METADATASTORE_PASSWORDFILE  | # Default path for the DB2 Password file to connect through the JDBC driver |  |
```suggestion
| DBB_MODELER_DB2_METADATASTORE_PASSWORDFILE  | Default path for the DB2 Password file to connect through the JDBC driver (recommended) |  |
```

2025-01-31 15:58 UTC, dennis-behm commented on Setup.sh
> +DBB_MODELER_DB2_METADATASTORE_ID="user"
Should we call it the `JDBC_USER` ?
```suggestion
DBB_MODELER_DB2_METADATASTORE_JDBCID="user"
```

2025-01-31 15:58 UTC, dennis-behm commented on src/groovy/assessUsage.groovy
> +	cli.f(longOpt:'file-metadatastore', args:1, 'Absolute path to the folder containing the DBB File MetadataStore')
Instead of `-` , I would rather prefer to have camelCase, like `fileMetadatastoreLocation`

2025-01-31 15:58 UTC, dennis-behm commented on src/groovy/scanApplication.groovy
> +logger.logMessage("** Storing results in the '${props.application}-main' DBB Collection.")
While I see that here - can we externalise the branch name to a property such as `defaultBranch`?

2025-01-31 15:58 UTC, dennis-behm commented on src/groovy/scanApplication.groovy
> +	cli.f(longOpt:'file-metadatastore', args:1, required:false, 'Absolute path to the folder containing the DBB File MetadataStore')
I think we are duplicating logic here by having the config, but then split it in the lower steps up.
Why not just pass in the modeller config and read it as a properties file?

2025-02-04 15:14 UTC, M-DLB commented on src/groovy/scanApplication.groovy
> +	cli.f(longOpt:'file-metadatastore', args:1, required:false, 'Absolute path to the folder containing the DBB File MetadataStore')
Done

2025-02-04 15:14 UTC, M-DLB commented on src/groovy/assessUsage.groovy
> +	cli.f(longOpt:'file-metadatastore', args:1, 'Absolute path to the folder containing the DBB File MetadataStore')
Changed because of it's now reading the Configuration file

2025-02-04 15:14 UTC, M-DLB commented on Setup.sh
> +DBB_MODELER_DB2_METADATASTORE_ID="user"
Changed

2025-02-04 15:15 UTC, M-DLB commented on src/groovy/scanApplication.groovy
> +logger.logMessage("** Storing results in the '${props.application}-main' DBB Collection.")
Should there be a DEFAULT_BRANCH parameter for the user to specify during Setup?

2025-02-04 15:20 UTC, dennis-behm commented on src/groovy/scanApplication.groovy
> +logger.logMessage("** Storing results in the '${props.application}-main' DBB Collection.")
Yes, let's create the parameter during the Setup. And we set the default to `main` .

2025-02-25 16:16 UTC, dennis-behm commented on Setup.sh
> +					echo "[WARNING] The minimal required version for the DBB Toolkit to use the Db2-based MetadataStore is 3.0.1."
Turn this into an error, and stop the Migration Modeler

2025-02-25 16:24 UTC, dennis-behm commented on src/groovy/assessUsage.groovy
> +	consumerApplicationDescriptorFile = new File("${Props.DBB_MODELER_APPLICATION_DIR}/${consumer}/applicationDescriptor.yml")
```suggestion
	consumerApplicationDescriptorFile = new File("${props.DBB_MODELER_APPLICATION_DIR}/${consumer}/applicationDescriptor.yml")
```

2025-02-26 08:42 UTC, M-DLB commented on src/groovy/checkDb2MetadataStore.groovy
> +@Field Properties configuration = new Properties()
Done

2025-02-26 08:42 UTC, M-DLB commented on src/groovy/scanApplication.groovy
> +@Field Properties configuration = new Properties()
Done

2025-02-26 08:42 UTC, M-DLB commented on src/groovy/recreateApplicationDescriptor.groovy
> +@Field Properties configuration = new Properties()
Done

2025-02-26 08:44 UTC, M-DLB commented on src/groovy/assessUsage.groovy
> +	consumerApplicationDescriptorFile = new File("${Props.DBB_MODELER_APPLICATION_DIR}/${consumer}/applicationDescriptor.yml")
Done at multiple locations

2025-02-26 08:46 UTC, M-DLB commented on src/groovy/checkDb2MetadataStore.groovy
> +Properties db2ConnectionProps = new Properties()
No, we're using a specific Properties object to just pass the Db2 MetadataStore info to DBB.

2025-02-26 09:10 UTC, M-DLB commented on Setup.sh
> +					echo "[WARNING] The DBB Toolkit is $dbbVersion and does not correctly support Db2-based MetadataStore!"
Done

2025-02-26 09:10 UTC, M-DLB commented on Setup.sh
> +					echo "[WARNING] The minimal required version for the DBB Toolkit to use the Db2-based MetadataStore is 3.0.1."
Done

2025-02-26 09:10 UTC, M-DLB commented on Setup.sh
> +	if [ "$validDBBVersion" -eq "0" ]; then
Done

2025-02-26 11:13 UTC, M-DLB commented on src/scripts/CheckDb2MetadataStore.sh
> +	CMD="$DBB_HOME/bin/groovyz $DBB_MODELER_HOME/src/groovy/checkDb2MetadataStore.groovy $@"
Changed that

2025-03-06 12:43 UTC, dennis-behm commented on src/groovy/scanApplication.groovy
> -@Field BuildProperties props = BuildProperties.getInstance()
These need to be of type BuildProperties (DBB extension of Properties), otherwise the controlTransfers variable is not considered.

2025-03-06 16:26 UTC, dennis-behm reviewed
@M-DLB one last change please

2025-03-07 08:37 UTC, M-DLB commented on src/groovy/extractApplications.groovy
> +logger.logMessage("** Reading the Type Mapping definition.")
Fixed

2025-03-12 15:33 UTC, dennis-behm commented on src/scripts/Migration-Modeler-Start.sh
> +					GitDistribution="Azure DevOps platform"
Probably not GitDistribution but "PipelineOrchestration"?

2025-03-13 12:16 UTC, dennis-behm approved these changes
@M-DLB Thanks for the hard work on this enhancement. Many thanks.

2025-03-13 13:08 UTC, merged