Reorganization of the repository layout
IBM/dbb-git-migration-modeler pull request #9
Opened 2024-06-12 14:32 UTC by M-DLB

This PR resolves #7 

Files were splitted by types, in `src/scripts` for Shell scripts, and in `src/groovy` for groovy scripts. Also, the configurations files were moved into the `samples` subfolder.
Documentation refined and updated accordingly.
A few minor bugs were also fixed along the way.

2024-06-14 07:42 UTC, dennis-behm commented
@M-DLB there are a couple of dead links on the README now due to the reorg. Getting a couple of 404's.

2024-06-14 09:44 UTC, M-DLB commented
> @M-DLB there are a couple of dead links on the README now due to the reorg. Getting a couple of 404's.

@dennis-behm Can you check again? All the links should be fixed now!

2024-06-17 11:17 UTC, dennis-behm requested changes
@M-DLB Thanks for restructuring the repo. I have a few (minor) areas, which could be improved. I made suggestions in the below comments.

Please note, that I did some formatting changes directly to the README.md.

2024-06-17 11:17 UTC, dennis-behm commented on README.md
>  For a given member analyzed by the utility, if its name doesn't match any of the naming convention, it will be associated to the *UNASSIGNED* application.
> For a given member analyzed by the utility, if its name doesn't match any of the naming convention, it will be associated to the *UNASSIGNED* application.

Simplify:

> Members on the input PDS libraries that do not  match any convention will be associated to the *UNASSIGNED* application and be treated as shared code.

2024-06-17 14:50 UTC, dennis-behm approved these changes
Thank you @M-DLB

2024-06-17 14:56 UTC, merged